import os

## DATABASE CONFIG

CONFIG_DATABASE_CONNECTION_STRING = os.environ["CONFIG_DATABASE_CONNECTION_STRING"]
CONFIG_DATABASE_NAME = os.environ["CONFIG_DATABASE_NAME"]

## SERVICE BUS CONFIG

CONFIG_SERVICE_BUS_CONNECTION_STRING = os.environ["CONFIG_SERVICE_BUS_CONNECTION_STRING"]
CONFIG_SERVICE_BUS_EMAIL_QUEUE = os.environ["CONFIG_SERVICE_BUS_EMAIL_QUEUE"]

## EMAIL SERVICE CONFIG

CONFIG_EMAIL_SERVICE_API_URL = os.environ["CONFIG_EMAIL_SERVICE_API_URL"]
CONFIG_EMAIL_SERVICE_API_KEY = os.environ["CONFIG_EMAIL_SERVICE_API_KEY"]
CONFIG_EMAIL_SERVICE_SENDER_EMAIL = os.environ["CONFIG_EMAIL_SERVICE_SENDER_EMAIL"]
CONFIG_EMAIL_SERVICE_TEMPLATE_ID = os.environ["CONFIG_EMAIL_SERVICE_TEMPLATE_ID"]